import os
import markdown
import pandas as pd
import streamlit as st

from database import get_conn

st.set_page_config(
    page_title="Project Reports",
    page_icon="📄",
    layout="wide"
)

st.title("📄 Project HTML Export")

# =====================================================
# LOAD PROJECTS
# =====================================================

conn = get_conn()

projects = pd.read_sql_query(
    """
    SELECT *
    FROM projects
    ORDER BY id DESC
    """,
    conn
)

conn.close()

if projects.empty:

    st.warning(
        "No project found."
    )

    st.stop()

# =====================================================
# SELECT PROJECT
# =====================================================

projects["display"] = (
    projects["id"].astype(str)
    + " - "
    + projects["name"]
)

selected_project = st.selectbox(
    "Select Project",
    projects["display"]
)

project_id = int(
    selected_project.split(" - ")[0]
)

# =====================================================
# LOAD PROJECT
# =====================================================

conn = get_conn()

project_df = pd.read_sql_query(
    """
    SELECT *
    FROM projects
    WHERE id = ?
    """,
    conn,
    params=[project_id]
)

if project_df.empty:

    conn.close()

    st.error(
        f"Project ID {project_id} not found"
    )

    st.stop()

project = project_df.iloc[0]

tasks = pd.read_sql_query(
    """
    SELECT *
    FROM tasks
    WHERE project_id = ?
    ORDER BY id
    """,
    conn,
    params=[project_id]
)

# =====================================================
# SUMMARY
# =====================================================

note_count = 0

for _, task in tasks.iterrows():

    notes = pd.read_sql_query(
        """
        SELECT *
        FROM notes
        WHERE task_id = ?
        """,
        conn,
        params=[task["id"]]
    )

    note_count += len(notes)

conn.close()

st.subheader("Summary")

c1, c2 = st.columns(2)

c1.metric(
    "Tasks",
    len(tasks)
)

c2.metric(
    "Notes",
    note_count
)

# =====================================================
# EXPORT HTML
# =====================================================

if st.button(
    "📄 Generate HTML Report"
):

    conn = get_conn()

    html = f"""
<!DOCTYPE html>
<html>

<head>

<meta charset="utf-8">

<title>{project['name']}</title>

<style>

body {{
    font-family: Arial, Helvetica, sans-serif;
    max-width: 1200px;
    margin: 40px auto;
    padding: 20px;
    line-height: 1.6;
}}

h1 {{
    color: #1565c0;
}}

.task {{
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 15px;
    margin-top: 20px;
}}

.note {{
    background: #f5f5f5;
    border-radius: 5px;
    padding: 12px;
    margin-top: 12px;
}}

.status {{
    font-weight: bold;
}}

.footer {{
    margin-top: 50px;
    font-size: 12px;
    color: #777;
}}
table {{
    border-collapse: collapse;
    width: 100%;
    margin-top: 10px;
}}

table th {{
    background: #f0f0f0;
}}

table th, table td {{
    border: 1px solid #ccc;
    padding: 8px;
    text-align: left;
}}

tr:nth-child(even) {{
    background: #fafafa;
}}
</style>

</head>

<body>

<h1>{project['name']}</h1>

<p>{project['description'] or ''}</p>

<hr>

<h2>Tasks</h2>

"""

    project_tasks = pd.read_sql_query(
        """
        SELECT *
        FROM tasks
        WHERE project_id = ?
        ORDER BY id
        """,
        conn,
        params=[project_id]
    )

    if project_tasks.empty:

        html += """
<p><i>No tasks found.</i></p>
"""

    else:

        for _, task in project_tasks.iterrows():

            html += f"""
<div class="task">

<h3>{task['title']}</h3>

<p>
<b>Status:</b> {task['status']}
</p>

<p>
<b>Priority:</b> {task['priority']}
</p>

<p>
<b>Due Date:</b> {task['due_date']}
</p>

<p>
{task['description'] or ''}
</p>

<h4>Notes</h4>
"""

            notes = pd.read_sql_query(
                """
                SELECT *
                FROM notes
                WHERE task_id = ?
                ORDER BY id DESC
                """,
                conn,
                params=[task["id"]]
            )

            if notes.empty:

                html += """
<p><i>No notes</i></p>
"""

            else:

                for _, note in notes.iterrows():

                    note_html = markdown.markdown(
                        note["content"],
                        extensions=[
                            "tables",
                            "fenced_code",
                            "toc",
                            "nl2br",
                            "sane_lists"
                        ]
                    )

                    html += f"""
<div class="note">

{note_html}

<hr>

<small>
Created: {note['created_at']}
</small>

</div>
"""

            html += """
</div>
"""

    html += """
<div class="footer">

Generated by Project Manager

</div>

</body>
</html>
"""

    conn.close()

    os.makedirs(
        "exports",
        exist_ok=True
    )

    file_name = (
        f"exports/project_{project_id}.html"
    )

    with open(
        file_name,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(html)

    st.success(
        f"Created: {file_name}"
    )

    with open(
        file_name,
        "rb"
    ) as f:

        st.download_button(
            label="⬇ Download HTML",
            data=f,
            file_name=f"{project['name']}.html",
            mime="text/html"
        )
